[build]
  functions = "."
  command = "echo Setting up..."
[functions]
  included_files = ["views/*", "public/*"]
  environment = { SERVERLESS = "1" }
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/app/:splat"