[build]
  functions = "functions-build"
[functions]
  external_node_modules = ["fastify"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/server/:splat"